# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src

# Install dependencies and build
RUN npm install --ignore-scripts && npm run build

# Expose any ports if needed (MCP over stdio, no ports)

# Default command to run the MCP server
CMD ["node", "dist/index.js"]
